"""Deterministic Codex artifacts generated from an explicit specialist hot set."""

import json
import re
from pathlib import Path, PurePosixPath

from lib.specialists import HotSet


_UNSAFE_CONTENT = re.compile(
    r"(?i)(?:api[_-]?key|access[_-]?token|client[_-]?secret|password)\s*[:=]|"
    r"[a-z]:\\users\\|/home/[^/\s]+/"
)


class CodexAdapter:
    ROOT_MODEL = "gpt-6.1-sol"
    ROOT_EFFORT = "medium"

    ROLE_SANDBOX = {
        "explorer": "read-only",
        "researcher": "read-only",
        "worker": "workspace-write",
        "hard-worker": "workspace-write",
        "tester": "workspace-write",
        "reviewer": "read-only",
        "architect": "read-only",
    }

    def render(self, hot_set: HotSet) -> dict[str, str]:
        config = [
            "# Generated by Galaxy Orchestrator. Do not edit.",
            f'model = "{self.ROOT_MODEL}"',
            f'model_reasoning_effort = "{self.ROOT_EFFORT}"',
            "",
            "[agents]",
            "enabled = true",
            "max_concurrent_threads_per_session = 3",
        ]
        artifacts: dict[str, str] = {}
        for role, sandbox in sorted(self.ROLE_SANDBOX.items()):
            config += [
                "",
                f"[agents.{role}]",
                f'description = "Galaxy {role}; bounded role authority."',
                f'config_file = "agents/{role}.toml"',
            ]
            artifacts[f".codex/agents/{role}.toml"] = (
                "# Generated by Galaxy Orchestrator. Do not edit.\n"
                f'sandbox_mode = "{sandbox}"\n'
                'developer_instructions = "Use only the explicit model and effort authorized by galaxy dispatch; obey the Galaxy task contract; do not expand authority or delegate."\n'
            )
        artifacts[".codex/config.toml"] = "\n".join(config) + "\n"
        compact = []
        for item in sorted(hot_set.specialists, key=lambda value: value.name):
            compact.append({"description": item.description, "name": item.name})
            frontmatter = [
                "---",
                f"name: {item.name}",
                f"description: {json.dumps(item.description, ensure_ascii=False)}",
                "---",
                "",
            ]
            artifacts[f".codex/skills/{item.name}/SKILL.md"] = (
                "\n".join(frontmatter) + item.body.rstrip() + "\n"
            )
        artifacts[".codex/galaxy-specialists.json"] = json.dumps(
            {"schema_version": 1, "specialists": compact},
            ensure_ascii=False,
            indent=2,
            sort_keys=True,
        ) + "\n"
        ordered = {name: artifacts[name] for name in sorted(artifacts)}
        self._validate(ordered)
        return ordered

    def materialize(self, project_root: Path, hot_set: HotSet) -> tuple[str, ...]:
        artifacts = self.render(hot_set)
        root = project_root.resolve()
        self._remove_stale_generated_skills(root, frozenset(hot_set.names))
        for relative, content in artifacts.items():
            pure = PurePosixPath(relative)
            if pure.is_absolute() or ".." in pure.parts:
                raise ValueError(f"unsafe adapter path: {relative}")
            target = root.joinpath(*pure.parts)
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(content, encoding="utf-8", newline="\n")
        return tuple(artifacts)

    @staticmethod
    def _remove_stale_generated_skills(root: Path, current: frozenset[str]) -> None:
        manifest = root / ".codex" / "galaxy-specialists.json"
        if not manifest.is_file():
            return
        try:
            previous = json.loads(manifest.read_text(encoding="utf-8"))
            names = {
                item["name"] for item in previous.get("specialists", [])
                if isinstance(item, dict) and isinstance(item.get("name"), str)
            }
        except (OSError, ValueError, TypeError):
            return
        safe_name = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")
        for name in sorted(names - current):
            if not safe_name.fullmatch(name):
                continue
            directory = root / ".codex" / "skills" / name
            skill = directory / "SKILL.md"
            if skill.is_file():
                skill.unlink()
            try:
                directory.rmdir()
            except OSError:
                pass

    @staticmethod
    def _validate(artifacts: dict[str, str]) -> None:
        for relative, content in artifacts.items():
            if _UNSAFE_CONTENT.search(content):
                raise ValueError(f"generated artifact contains a secret or local path: {relative}")
