"""Deterministic, local-only Galaxy project bootstrap."""

from __future__ import annotations

import hashlib
import json
import os
import tempfile
import stat
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any

from lib.project import (
    LOCAL_IGNORE_PATHS,
    GalaxyProject,
    declarations_unchanged,
    load_project,
    project_pollution,
)


class BootstrapError(ValueError):
    """Bootstrap cannot safely reproduce the requested local environment."""


@dataclass(frozen=True)
class BootstrapPlan:
    project: GalaxyProject
    artifacts: tuple[tuple[str, bytes], ...]
    create: tuple[str, ...]
    update: tuple[str, ...]
    remove: tuple[str, ...]
    unchanged: tuple[str, ...]
    drift: tuple[str, ...]
    previous: tuple[tuple[str, bytes], ...]
    removal_previous: tuple[tuple[str, bytes], ...]
    pollution: Any
    vault: str
    state_snapshot: bytes | None
    state_hashes: tuple[tuple[str, str], ...]

    @property
    def clean(self) -> bool:
        return not self.create and not self.update and not self.remove and not self.drift


@dataclass(frozen=True)
class BootstrapResult:
    applied: bool
    written: tuple[str, ...]
    create: tuple[str, ...]
    update: tuple[str, ...]
    removed: tuple[str, ...]
    unchanged: tuple[str, ...]
    drift: tuple[str, ...]
    pollution: Any
    vault: str


def _catalog(root: Path):
    try:
        from lib.specialists import SpecialistCatalog
    except ImportError as exc:
        raise BootstrapError("Codex specialist catalog is unavailable") from exc
    return SpecialistCatalog.from_directory(root)


def _catalog_revision(catalog: Any) -> str:
    try:
        from lib.specialists import build_index
    except ImportError as exc:
        raise BootstrapError("specialist index implementation is unavailable") from exc
    return hashlib.sha256(build_index(catalog).encode("utf-8")).hexdigest()


def _renderer(renderer: Any | None):
    if renderer is not None:
        return renderer
    try:
        from lib.adapters.codex import CodexAdapter
    except ImportError as exc:
        raise BootstrapError("Codex adapter is unavailable") from exc
    return CodexAdapter()


def _generated(relative: str, content: str | bytes) -> bytes:
    raw = content.encode("utf-8") if isinstance(content, str) else bytes(content)
    if relative.endswith(".json"):
        try:
            value = json.loads(raw.decode("utf-8"))
        except (UnicodeError, json.JSONDecodeError) as exc:
            raise BootstrapError(f"adapter returned invalid JSON: {relative}") from exc
        if not isinstance(value, dict):
            raise BootstrapError(f"generated JSON must be an object: {relative}")
        value = dict(value)
        value["_galaxy_generated"] = {
            "notice": "GENERATED BY GALAXY - DO NOT EDIT DIRECTLY",
            "source": "galaxy.lock",
        }
        return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")
    text = raw.decode("utf-8")
    if relative.endswith(".md"):
        marker = "<!-- GENERATED BY GALAXY - DO NOT EDIT DIRECTLY; source: galaxy.lock -->\n"
        if text.startswith("---\n"):
            end = text.find("\n---\n", 4)
            if end >= 0:
                offset = end + len("\n---\n")
                return (text[:offset] + marker + text[offset:]).encode("utf-8")
        return (marker + text).encode("utf-8")
    comment = "# GENERATED BY GALAXY - DO NOT EDIT DIRECTLY\n# source: galaxy.lock\n"
    return (comment + text).encode("utf-8")


def _safe_artifacts(rendered: Any) -> tuple[tuple[str, bytes], ...]:
    if not isinstance(rendered, dict):
        raise BootstrapError("adapter renderer must return a path-to-content mapping")
    artifacts = []
    for relative, content in rendered.items():
        if not isinstance(relative, str) or not isinstance(content, (str, bytes)):
            raise BootstrapError("adapter output paths and content must be strings or bytes")
        pure = PurePosixPath(relative.replace("\\", "/"))
        if pure.is_absolute() or ".." in pure.parts or not pure.parts or pure.parts[0] != ".codex":
            raise BootstrapError(f"adapter attempted to write outside .codex: {relative}")
        artifacts.append((pure.as_posix(), _generated(pure.as_posix(), content)))
    return tuple(sorted(artifacts))


def _is_galaxy_generated(relative: str, content: bytes) -> bool:
    if relative.endswith(".json"):
        try:
            value = json.loads(content.decode("utf-8"))
        except (UnicodeError, json.JSONDecodeError):
            return False
        return isinstance(value, dict) and isinstance(value.get("_galaxy_generated"), dict)
    return b"GENERATED BY GALAXY" in content[:1024]


_STATE_RELATIVE = ".galaxy/install/bootstrap-state.json"


def _digest(content: bytes) -> str:
    return hashlib.sha256(content).hexdigest()


def _read_bootstrap_state(project: GalaxyProject) -> tuple[bytes | None, dict[str, str] | None]:
    path = _assert_local_target(project, _STATE_RELATIVE)
    try:
        raw = path.read_bytes()
    except FileNotFoundError:
        return None, None
    except OSError as exc:
        raise BootstrapError(f"cannot read bootstrap state: {exc}") from exc
    try:
        decoded = json.loads(raw.decode("utf-8"))
    except (UnicodeError, json.JSONDecodeError):
        return raw, None
    if not isinstance(decoded, dict):
        return raw, None
    artifacts = decoded.get("artifacts")
    if (
        decoded.get("schema_version") != 1
        or not isinstance(artifacts, dict)
        or any(
            not isinstance(key, str)
            or not isinstance(value, str)
            or len(value) != 64
            or any(character not in "0123456789abcdef" for character in value)
            for key, value in artifacts.items()
        )
    ):
        return raw, None
    return raw, dict(artifacts)


def _bootstrap_state_bytes(hashes: dict[str, str]) -> bytes:
    return (json.dumps(
        {"schema_version": 1, "artifacts": dict(sorted(hashes.items()))},
        ensure_ascii=False, indent=2, sort_keys=True,
    ) + "\n").encode("utf-8")


def _assert_local_target(project: GalaxyProject, relative: str) -> Path:
    target = project.root.joinpath(*PurePosixPath(relative).parts)
    current = project.root
    for part in PurePosixPath(relative).parts:
        current = current / part
        if current.exists() or current.is_symlink():
            info = current.lstat()
            is_reparse = bool(
                getattr(info, "st_file_attributes", 0)
                & getattr(stat, "FILE_ATTRIBUTE_REPARSE_POINT", 0x400)
            )
            if current.is_symlink() or is_reparse:
                raise BootstrapError(f"bootstrap target contains a symlink/reparse point: {relative}")
    return target


def _stale_skills(
    project: GalaxyProject,
    selected: frozenset[str],
    recorded: dict[str, str] | None,
) -> tuple[tuple[str, bytes], ...]:
    manifest = project.root / ".codex/galaxy-specialists.json"
    if not manifest.is_file():
        return ()
    try:
        value = json.loads(manifest.read_text(encoding="utf-8"))
        previous = {
            item["name"] for item in value.get("specialists", [])
            if isinstance(item, dict) and isinstance(item.get("name"), str)
        }
    except (OSError, UnicodeError, json.JSONDecodeError, TypeError):
        return ()
    stale = []
    for name in sorted(previous - selected):
        if not name or any(character not in "abcdefghijklmnopqrstuvwxyz0123456789-" for character in name):
            continue
        relative = f".codex/skills/{name}/SKILL.md"
        target = _assert_local_target(project, relative)
        if target.is_file():
            content = target.read_bytes()
            if not recorded or recorded.get(relative) != _digest(content):
                raise BootstrapError(f"stale specialist contains non-generated content: {relative}")
            stale.append((relative, content))
    return tuple(stale)


def _vault_state(project: GalaxyProject) -> str:
    vault = project.config.vault
    if not vault.get("enabled", False):
        return "disabled"
    # Bootstrap validates the tracked, project-relative declaration but leaves all
    # vault I/O to the explicit vault sync command.  In particular, it never reads
    # operator.toml or follows a private external-vault path implicitly.
    return "configured-not-synced"


def _exclude_artifact(project: GalaxyProject) -> tuple[str, bytes] | None:
    git_dir = project.root / ".git"
    if not git_dir.is_dir():
        return None
    paths = list(LOCAL_IGNORE_PATHS)
    vault = project.config.vault
    if vault.get("enabled", False) and vault.get("mode", "projection") == "projection":
        path = str(vault.get("path", ".galaxy/vault")).replace("\\", "/").rstrip("/") + "/"
        paths.append(path)
    begin = b"# BEGIN Galaxy Orchestrator local/generated artifacts"
    end = b"# END Galaxy Orchestrator local/generated artifacts"
    block = begin + b"\n" + "".join(path + "\n" for path in dict.fromkeys(paths)).encode("utf-8") + end + b"\n"
    exclude = git_dir / "info/exclude"
    try:
        current = exclude.read_bytes()
    except FileNotFoundError:
        current = b""
    except OSError as exc:
        raise BootstrapError(f"cannot read local Git exclude policy: {exc}") from exc
    if begin in current:
        start = current.index(begin)
        finish = current.find(end, start)
        if finish < 0:
            raise BootstrapError("local Git exclude contains an incomplete Galaxy managed block")
        finish += len(end)
        if finish < len(current) and current[finish:finish + 2] == b"\r\n":
            finish += 2
        elif finish < len(current) and current[finish:finish + 1] == b"\n":
            finish += 1
        expected = current[:start] + block + current[finish:]
    else:
        separator = b"" if not current or current.endswith(b"\n") else b"\n"
        expected = current + separator + block
    return ".git/info/exclude", expected


def bootstrap_plan(
    project_root: Path | str,
    *,
    catalog_root: Path | str | None = None,
    renderer: Any | None = None,
    verify_catalog: bool = True,
) -> BootstrapPlan:
    """Build a complete dry-run plan.  This function performs no writes."""
    project = load_project(project_root)
    state_snapshot, recorded = _read_bootstrap_state(project)
    catalog_path = Path(catalog_root) if catalog_root is not None else Path(__file__).parents[1] / "specialists"
    catalog = _catalog(catalog_path)
    if verify_catalog:
        effective = _catalog_revision(catalog)
        if effective != project.lock.catalog_revision:
            raise BootstrapError(
                "specialist catalog revision does not match galaxy.lock "
                f"(expected {project.lock.catalog_revision}, got {effective})"
            )
    try:
        hot_set = catalog.hot_set(
            packs=project.selected_packs,
            names=project.selected_specialists,
        )
    except KeyError as exc:
        raise BootstrapError(str(exc)) from exc
    artifacts = list(_safe_artifacts(_renderer(renderer).render(hot_set)))
    removal_previous = _stale_skills(project, frozenset(hot_set.names), recorded)
    remove = tuple(relative for relative, _content in removal_previous)
    exclude = _exclude_artifact(project)
    if exclude:
        artifacts.append(exclude)
    artifacts.sort()
    create, update, unchanged, drift, previous = [], [], [], [], []
    for relative, expected in artifacts:
        target = _assert_local_target(project, relative)
        if not target.exists():
            create.append(relative)
        elif (
            relative == ".git/info/exclude"
            and b"# BEGIN Galaxy Orchestrator local/generated artifacts" not in target.read_bytes()
        ):
            # Adding Galaxy's delimited block preserves an existing user-local
            # exclude file; it is an initialization, not user drift.
            create.append(relative)
        else:
            current = target.read_bytes() if target.is_file() else b""
            if current == expected:
                unchanged.append(relative)
            elif relative == ".git/info/exclude" or (
                recorded is not None and recorded.get(relative) == _digest(current)
            ):
                update.append(relative)
                previous.append((relative, current))
            else:
                drift.append(relative)
    state_hashes = tuple(sorted(
        (relative, _digest(content))
        for relative, content in artifacts
        if relative != ".git/info/exclude"
    ))
    return BootstrapPlan(
        project, tuple(artifacts), tuple(create), tuple(update), remove, tuple(unchanged), tuple(drift),
        tuple(previous), removal_previous,
        project_pollution(project.root), _vault_state(project),
        state_snapshot, state_hashes,
    )


def _atomic_write(path: Path, content: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix=f".{path.name}.", suffix=".tmp", dir=path.parent)
    try:
        with os.fdopen(descriptor, "wb") as stream:
            stream.write(content)
            stream.flush()
            os.fsync(stream.fileno())
        os.replace(temporary, path)
    except BaseException:
        try:
            os.unlink(temporary)
        except FileNotFoundError:
            pass
        raise


def bootstrap(
    project_root: Path | str,
    *,
    check: bool = False,
    catalog_root: Path | str | None = None,
    renderer: Any | None = None,
    verify_catalog: bool = True,
) -> BootstrapResult:
    """Check or apply deterministic local artifacts.

    Existing divergent generated files are never overwritten, and the tracked
    declarations are rechecked immediately before materialization.
    """
    plan = bootstrap_plan(
        project_root, catalog_root=catalog_root, renderer=renderer,
        verify_catalog=verify_catalog,
    )
    if check:
        return BootstrapResult(False, (), plan.create, plan.update, plan.remove, plan.unchanged, plan.drift, plan.pollution, plan.vault)
    if plan.drift:
        raise BootstrapError("generated artifact drift detected: " + ", ".join(plan.drift))
    if not declarations_unchanged(plan.project):
        raise BootstrapError("project-owned declarations changed during bootstrap; retry after review")
    state_path = _assert_local_target(plan.project, _STATE_RELATIVE)
    current_state = state_path.read_bytes() if state_path.is_file() else None
    if current_state != plan.state_snapshot:
        raise BootstrapError("bootstrap state changed concurrently")
    expected = dict(plan.artifacts)
    previous = dict(plan.previous)
    removal_previous = dict(plan.removal_previous)
    for relative in plan.create + plan.update:
        if not declarations_unchanged(plan.project):
            raise BootstrapError("project-owned declarations changed during bootstrap; refusing partial overwrite")
        target = _assert_local_target(plan.project, relative)
        if relative in previous:
            if not target.is_file() or target.read_bytes() != previous[relative]:
                raise BootstrapError(f"bootstrap target changed concurrently: {relative}")
        elif target.exists():
            if relative != ".git/info/exclude":
                raise BootstrapError(f"bootstrap target changed concurrently: {relative}")
            current = target.read_bytes()
            marker = b"# BEGIN Galaxy Orchestrator local/generated artifacts"
            if marker in current or not expected[relative].startswith(current):
                raise BootstrapError(f"bootstrap target changed concurrently: {relative}")
        _atomic_write(target, expected[relative])
    for relative in plan.remove:
        target = _assert_local_target(plan.project, relative)
        if (
            not target.is_file()
            or target.read_bytes() != removal_previous.get(relative)
        ):
            raise BootstrapError(f"stale generated specialist changed concurrently: {relative}")
        target.unlink()
        try:
            target.parent.rmdir()
        except OSError:
            pass
    if not declarations_unchanged(plan.project):
        raise BootstrapError("project-owned declarations changed during bootstrap; refusing state advancement")
    current_state = state_path.read_bytes() if state_path.is_file() else None
    if current_state != plan.state_snapshot:
        raise BootstrapError("bootstrap state changed concurrently")
    desired_state = _bootstrap_state_bytes(dict(plan.state_hashes))
    if current_state != desired_state:
        _atomic_write(state_path, desired_state)
    written = plan.create + plan.update
    return BootstrapResult(True, written, plan.create, plan.update, plan.remove, plan.unchanged, (), plan.pollution, plan.vault)


# Friendly aliases for callers that name the operation explicitly.
plan_bootstrap = bootstrap_plan
bootstrap_project = bootstrap


__all__ = [
    "BootstrapError", "BootstrapPlan", "BootstrapResult", "bootstrap",
    "bootstrap_plan", "bootstrap_project", "plan_bootstrap",
]
