import json
from unittest.mock import patch
import shutil
import subprocess
import tempfile
import unittest
from pathlib import Path

from lib.bootstrap import BootstrapError, bootstrap, bootstrap_plan

from tests.bootstrap.test_project import update_declaration_hashes, write_project


class FakeRenderer:
    def render(self, hot_set):
        names = ",".join(hot_set.names)
        return {
            ".codex/agents/root.toml": 'model = "gpt-5.6-sol"\nreasoning_effort = "medium"\n',
            ".codex/hot.txt": names + "\n",
        }


class EvolvedRenderer(FakeRenderer):
    def render(self, hot_set):
        result = super().render(hot_set)
        result[".codex/hot.txt"] = "evolved\n"
        return result


class BootstrapTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory()
        self.addCleanup(self.temporary.cleanup)
        self.root = Path(self.temporary.name) / "project"
        self.root.mkdir()
        write_project(self.root)
        catalog = Path(__file__).parents[2] / "specialists"
        self.catalog = catalog

    def test_preview_and_check_have_no_writes(self):
        plan = bootstrap_plan(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        self.assertIn(".codex/agents/root.toml", plan.create)
        result = bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), check=True, verify_catalog=False)
        self.assertFalse(result.applied)
        self.assertIn(".codex/agents/root.toml", result.create)
        self.assertFalse((self.root / ".codex").exists())

    def test_apply_is_deterministic_generated_and_does_not_vendor_tools(self):
        first = bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        before = {p.relative_to(self.root).as_posix(): p.read_bytes() for p in self.root.rglob("*") if p.is_file()}
        second = bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        after = {p.relative_to(self.root).as_posix(): p.read_bytes() for p in self.root.rglob("*") if p.is_file()}
        self.assertTrue(first.applied)
        self.assertEqual(before, after)
        self.assertEqual(second.written, ())
        root_agent = (self.root / ".codex/agents/root.toml").read_text()
        self.assertIn("GENERATED BY GALAXY", root_agent)
        self.assertIn('reasoning_effort = "medium"', root_agent)
        self.assertEqual((self.root / ".codex/hot.txt").read_text().splitlines()[-1], "core,git")
        self.assertFalse((self.root / ".multicontroller/tools").exists())
        self.assertFalse((self.root / ".galaxy/tools").exists())
        state = json.loads((self.root / ".galaxy/install/bootstrap-state.json").read_text())
        self.assertEqual(state["schema_version"], 1)
        self.assertIn(".codex/hot.txt", state["artifacts"])

    def test_template_evolution_updates_only_bytes_recorded_as_generated(self):
        bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)

        result = bootstrap(
            self.root, catalog_root=self.catalog, renderer=EvolvedRenderer(), verify_catalog=False,
        )

        self.assertIn(".codex/hot.txt", result.update)
        self.assertEqual((self.root / ".codex/hot.txt").read_text().splitlines()[-1], "evolved")

    def test_marker_retaining_user_edit_is_drift_and_preserved(self):
        bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        target = self.root / ".codex/hot.txt"
        edited = target.read_bytes().replace(b"core,git", b"human-choice")
        target.write_bytes(edited)

        with self.assertRaisesRegex(BootstrapError, "drift"):
            bootstrap(self.root, catalog_root=self.catalog, renderer=EvolvedRenderer(), verify_catalog=False)

        self.assertEqual(target.read_bytes(), edited)

    def test_missing_or_corrupt_state_cannot_authorize_template_evolution(self):
        for index, content in enumerate((None, b"not-json", b"[]")):
            with self.subTest(content=content):
                root = Path(self.temporary.name) / f"state-case-{index}"
                root.mkdir()
                write_project(root)
                bootstrap(root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
                state = root / ".galaxy/install/bootstrap-state.json"
                if content is None:
                    state.unlink()
                else:
                    state.write_bytes(content)
                before = (root / ".codex/hot.txt").read_bytes()
                with self.assertRaisesRegex(BootstrapError, "drift"):
                    bootstrap(root, catalog_root=self.catalog, renderer=EvolvedRenderer(), verify_catalog=False)
                self.assertEqual((root / ".codex/hot.txt").read_bytes(), before)

    def test_failed_artifact_application_does_not_advance_bootstrap_state(self):
        bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        state = self.root / ".galaxy/install/bootstrap-state.json"
        before = state.read_bytes()
        real_atomic_write = __import__("lib.bootstrap", fromlist=["_atomic_write"])._atomic_write

        def fail_second(path, content):
            if Path(path).as_posix().endswith("/.codex/hot.txt"):
                raise OSError("simulated write failure")
            return real_atomic_write(path, content)

        with patch("lib.bootstrap._atomic_write", side_effect=fail_second):
            with self.assertRaisesRegex(OSError, "simulated write failure"):
                bootstrap(
                    self.root, catalog_root=self.catalog, renderer=EvolvedRenderer(),
                    verify_catalog=False,
                )
        self.assertEqual(state.read_bytes(), before)

    def test_generated_drift_is_refused_and_declarations_are_unchanged(self):
        declaration = self.root / ".galaxy/project.yml"
        original = declaration.read_bytes()
        bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        (self.root / ".codex/hot.txt").write_text("human edit")
        with self.assertRaises(BootstrapError):
            bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        self.assertEqual(declaration.read_bytes(), original)

    def test_fresh_clones_reproduce_identical_adapter_outputs(self):
        other = Path(self.temporary.name) / "clone"
        other.mkdir()
        write_project(other)
        for root in (self.root, other):
            bootstrap(root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        one = {p.relative_to(self.root).as_posix(): p.read_bytes() for p in (self.root / ".codex").rglob("*") if p.is_file()}
        two = {p.relative_to(other).as_posix(): p.read_bytes() for p in (other / ".codex").rglob("*") if p.is_file()}
        self.assertEqual(one, two)

    def test_vault_is_opt_in_and_bootstrap_never_opens_external_path(self):
        config_path = self.root / ".galaxy/project.yml"
        config = json.loads(config_path.read_text())
        config["vault"] = {"enabled": False, "path": ".galaxy/vault", "mode": "projection"}
        config_path.write_text(json.dumps(config))
        update_declaration_hashes(self.root)
        result = bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        self.assertEqual(result.vault, "disabled")
        self.assertFalse((self.root / ".galaxy/vault").exists())

    def test_repository_template_bootstraps_with_real_codex_adapter(self):
        template = Path(__file__).parents[2] / "template"
        target = Path(self.temporary.name) / "from-template"
        shutil.copytree(template / ".galaxy", target / ".galaxy")
        shutil.copy2(template / "AGENTS.md", target / "AGENTS.md")
        shutil.copy2(template / "galaxy.lock", target / "galaxy.lock")
        result = bootstrap(target, catalog_root=self.catalog)
        self.assertTrue(result.applied)
        root_config = (target / ".codex/config.toml").read_text(encoding="utf-8")
        self.assertIn('model = "gpt-5.6-sol"', root_config)
        self.assertIn('model_reasoning_effort = "medium"', root_config)
        self.assertEqual(
            sorted(path.parent.name for path in (target / ".codex/skills").glob("*/SKILL.md")),
            ["core"],
        )

    def test_git_exclude_preserves_user_policy_and_adds_local_paths(self):
        if subprocess.run(["git", "--version"], capture_output=True).returncode:
            self.skipTest("Git unavailable")
        subprocess.run(["git", "init", "-q"], cwd=self.root, check=True)
        exclude = self.root / ".git/info/exclude"
        exclude.write_text("user-local.txt\n", encoding="utf-8")
        bootstrap(self.root, catalog_root=self.catalog, renderer=FakeRenderer(), verify_catalog=False)
        content = exclude.read_text(encoding="utf-8")
        self.assertIn("user-local.txt", content)
        for relative in (".codex/", ".galaxy/local/", ".galaxy/runtime/", ".galaxy/cache/", ".galaxy/install/"):
            self.assertIn(relative, content)

    def test_changed_hot_set_replaces_only_proven_generated_specialists(self):
        template = Path(__file__).parents[2] / "template"
        target = Path(self.temporary.name) / "hot-set-change"
        shutil.copytree(template / ".galaxy", target / ".galaxy")
        shutil.copy2(template / "AGENTS.md", target / "AGENTS.md")
        shutil.copy2(template / "galaxy.lock", target / "galaxy.lock")
        bootstrap(target, catalog_root=self.catalog)
        config_path = target / ".galaxy/project.yml"
        config = json.loads(config_path.read_text())
        config["specialists"] = {"packs": ["git"], "names": []}
        config_path.write_text(json.dumps(config), encoding="utf-8")
        lock_path = target / "galaxy.lock"
        lock = json.loads(lock_path.read_text())
        lock["specialists"]["packs"] = ["git"]
        lock_path.write_text(json.dumps(lock), encoding="utf-8")
        update_declaration_hashes(target)
        result = bootstrap(target, catalog_root=self.catalog)
        self.assertIn(".codex/skills/core/SKILL.md", result.removed)
        self.assertFalse((target / ".codex/skills/core").exists())
        self.assertTrue((target / ".codex/skills/git/SKILL.md").is_file())

    def test_stale_specialist_marker_edit_after_plan_is_preserved(self):
        template = Path(__file__).parents[2] / "template"
        target = Path(self.temporary.name) / "stale-race"
        shutil.copytree(template / ".galaxy", target / ".galaxy")
        shutil.copy2(template / "AGENTS.md", target / "AGENTS.md")
        shutil.copy2(template / "galaxy.lock", target / "galaxy.lock")
        bootstrap(target, catalog_root=self.catalog)
        project_path = target / ".galaxy/project.yml"
        lock_path = target / "galaxy.lock"
        project = json.loads(project_path.read_text())
        lock = json.loads(lock_path.read_text())
        project["specialists"]["packs"] = ["git"]
        lock["specialists"]["packs"] = ["git"]
        project_path.write_text(json.dumps(project), encoding="utf-8")
        lock_path.write_text(json.dumps(lock), encoding="utf-8")
        update_declaration_hashes(target)
        plan = bootstrap_plan(target, catalog_root=self.catalog)
        stale = target / ".codex/skills/core/SKILL.md"
        edited = stale.read_bytes() + b"\n<!-- GENERATED BY GALAXY user-preserved note -->\n"
        stale.write_bytes(edited)

        with patch("lib.bootstrap.bootstrap_plan", return_value=plan):
            with self.assertRaisesRegex(BootstrapError, "changed concurrently"):
                bootstrap(target, catalog_root=self.catalog)

        self.assertEqual(stale.read_bytes(), edited)


if __name__ == "__main__":
    unittest.main()
