import hashlib
import json
import subprocess
import tempfile
import unittest
from pathlib import Path

from lib.migrations import (
    MigrationConflictError,
    apply,
    plan,
    rollback,
)


def _json(value):
    return (json.dumps(value, indent=2, sort_keys=True) + "\n").encode()


def _git(root, *args):
    return subprocess.run(
        ["git", *args], cwd=root, check=True, capture_output=True, text=True
    ).stdout.strip()


class MigrationFixture:
    def __init__(self, root: Path):
        self.root = root
        self.files = {
            "AGENT_TEAM.yml": _json({
                "schema_version": 3,
                "mode": "SOLO",
                "integration_branch": "main",
                "operators": [],
                "required_checks": ["multicontroller / validate"],
            }),
            ".multicontroller/checks.json": _json({"commands": []}),
            ".multicontroller/policy.json": _json({
                "schema_version": 1,
                "preset": "balanced",
                "max_subagents": 3,
            }),
            ".codex/config.toml": b'model = "gpt-5.6-sol"\n',
            ".agents/skills/multicontroller/SKILL.md": b"legacy skill\n",
            ".multicontroller/tools/multicontroller.py": b"legacy tool\n",
            ".multicontroller/examples/gate.json": b"{}\n",
            ".multicontroller/messages/HANDOFF.md": b"handoff\n",
            ".github/workflows/multicontroller.yml": b"name: multicontroller\n",
        }
        for name, data in self.files.items():
            path = root / name
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_bytes(data)
        manifest = {
            "schema_version": 1,
            "version": "1.3.0",
            "mode": "SOLO",
            "preset": "balanced",
            "files": {
                name: hashlib.sha256(data).hexdigest()
                for name, data in self.files.items()
            },
        }
        path = root / ".multicontroller/install-manifest.json"
        path.write_bytes(_json(manifest))
        self.files[".multicontroller/install-manifest.json"] = path.read_bytes()


class MigrationTests(unittest.TestCase):
    def setUp(self):
        self.temporary = tempfile.TemporaryDirectory(prefix="galaxy migration ")
        self.addCleanup(self.temporary.cleanup)
        base = Path(self.temporary.name)
        self.master = base / "master"
        self.project = base / "project"
        self.master.mkdir()
        self.project.mkdir()
        (self.master / "VERSION").write_text("2.0.0\n")
        self.fixture = MigrationFixture(self.project)

    def snapshot(self):
        return {
            path.relative_to(self.project).as_posix(): path.read_bytes()
            for path in self.project.rglob("*") if path.is_file()
        }

    def test_clean_preview_has_no_side_effects(self):
        (self.project / ".gitignore").write_text(".env\n", encoding="utf-8")
        before = self.snapshot()
        result = plan(self.master, self.project)
        self.assertTrue(result.ready)
        self.assertIn("AGENT_TEAM.yml", result.project_owned)
        self.assertIn(".codex/config.toml", result.managed_unchanged)
        self.assertEqual(before, self.snapshot())
        self.assertFalse((self.master / "local").exists())
        receipt = apply(self.master, self.project)
        self.assertIn(b".env", (self.project / ".gitignore").read_bytes())
        self.assertEqual(receipt["status"], "success")
        generated = (self.project / ".codex/config.toml").read_text(encoding="utf-8")
        self.assertIn("GENERATED BY GALAXY", generated)
        self.assertIn('model_reasoning_effort = "medium"', generated)
        self.assertEqual(receipt["bootstrap"]["status"], "passed")

    def test_customized_team_is_semantically_preserved(self):
        team_path = self.project / "AGENT_TEAM.yml"
        team = json.loads(team_path.read_text())
        team["integration_branch"] = "develop"
        team["custom"] = {"owner": "project"}
        team_path.write_bytes(_json(team))
        checks_path = self.project / ".multicontroller/checks.json"
        checks_path.write_bytes(_json({"commands": [["python", "-m", "unittest"]]}))
        receipt = apply(self.master, self.project)
        migrated = json.loads((self.project / ".galaxy/team.yml").read_text())
        self.assertEqual(migrated["integration_branch"], "develop")
        self.assertEqual(migrated["custom"], {"owner": "project"})
        self.assertEqual(migrated["required_checks"], ["galaxy / validate"])
        self.assertFalse(team_path.exists())
        self.assertEqual(
            json.loads((self.project / ".galaxy/checks.json").read_text())["commands"],
            [["python", "-m", "unittest"]],
        )
        self.assertEqual(receipt["status"], "success")

    def test_modified_managed_file_blocks_without_project_mutation(self):
        target = self.project / ".codex/config.toml"
        target.write_text("human change\n")
        before = self.snapshot()
        migration_plan = plan(self.master, self.project)
        self.assertIn(".codex/config.toml", migration_plan.managed_user_modified)
        with self.assertRaises(MigrationConflictError):
            apply(self.master, self.project)
        self.assertEqual(before, self.snapshot())
        self.assertFalse((self.project / "galaxy.lock").exists())

    def test_tracked_codex_is_untracked_without_deleting_working_copy(self):
        _git(self.project, "init", "-q")
        _git(self.project, "add", ".")
        observed = []
        def validate(root):
            observed.extend(_git(root, "ls-files").splitlines())
            return {"status": "passed"}
        receipt = apply(self.master, self.project, validator=validate)
        self.assertTrue((self.project / ".codex/config.toml").exists())
        self.assertIn(".codex/config.toml", observed)
        self.assertNotIn(".codex/config.toml", _git(self.project, "ls-files").splitlines())
        self.assertIn(".codex/config.toml", receipt["untracked"])

    def test_mixed_agents_content_is_preserved_and_not_untracked(self):
        owned = self.project / ".agents/skills/team-owned/SKILL.md"
        owned.parent.mkdir(parents=True)
        owned.write_text("project content\n")
        _git(self.project, "init", "-q")
        _git(self.project, "add", ".")
        receipt = apply(self.master, self.project)
        tracked = _git(self.project, "ls-files").splitlines()
        self.assertTrue(owned.exists())
        self.assertIn(".agents/skills/team-owned/SKILL.md", tracked)
        self.assertNotIn(".agents/skills/multicontroller/SKILL.md", tracked)
        self.assertIn(".agents/skills/team-owned/SKILL.md", receipt["preserved"])

    def test_failed_validation_rolls_back_files_and_git_index_exactly(self):
        _git(self.project, "init", "-q")
        _git(self.project, "add", ".")
        before = self.snapshot()
        before_index = (self.project / ".git/index").read_bytes()
        with self.assertRaisesRegex(ValueError, "validation failed"):
            apply(
                self.master,
                self.project,
                validator=lambda _root: (_ for _ in ()).throw(ValueError("validation failed")),
            )
        self.assertEqual(before, self.snapshot())
        self.assertEqual(before_index, (self.project / ".git/index").read_bytes())

    def test_bootstrap_drift_rolls_back_declarations_and_git_index_exactly(self):
        drift = self.project / ".codex/agents/worker.toml"
        drift.parent.mkdir(parents=True, exist_ok=True)
        drift.write_bytes(b"project-owned runtime collision\n")
        _git(self.project, "init", "-q")
        _git(self.project, "add", ".")
        before = self.snapshot()
        before_index = (self.project / ".git/index").read_bytes()
        with self.assertRaisesRegex(ValueError, "drift"):
            apply(self.master, self.project)
        self.assertEqual(before, self.snapshot())
        self.assertEqual(before_index, (self.project / ".git/index").read_bytes())

    def test_success_receipt_can_restore_exact_files_and_index(self):
        _git(self.project, "init", "-q")
        _git(self.project, "add", ".")
        before = self.snapshot()
        before_index = (self.project / ".git/index").read_bytes()
        receipt = apply(self.master, self.project)
        for field in (
            "transformed", "preserved", "untracked", "generated", "conflicts",
            "validation", "doctor", "backup_location", "receipt_path",
        ):
            self.assertIn(field, receipt)
        result = rollback(self.master, self.project, receipt["receipt_path"])
        self.assertEqual(result["status"], "rolled_back")
        self.assertEqual(before, self.snapshot())
        self.assertEqual(before_index, (self.project / ".git/index").read_bytes())

    def test_vault_is_inventory_only_and_apply_is_idempotent(self):
        vault = self.project / ".multicontroller/vault/tasks/private.md"
        vault.parent.mkdir(parents=True)
        vault.write_bytes(b"user vault bytes\n")
        migration_plan = plan(self.master, self.project)
        self.assertIn(".multicontroller/vault", migration_plan.vault_inventory)
        apply(self.master, self.project)
        self.assertEqual(vault.read_bytes(), b"user vault bytes\n")
        second = apply(self.master, self.project)
        self.assertEqual(second["status"], "already_migrated")
        self.assertEqual(vault.read_bytes(), b"user vault bytes\n")


if __name__ == "__main__":
    unittest.main()
